# Generated by Django 3.0 on 2022-04-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名前')),
                ('hit_points', models.IntegerField(verbose_name='HP')),
                ('attack', models.IntegerField(verbose_name='攻撃')),
                ('defense', models.IntegerField(verbose_name='防御')),
                ('special_attack', models.IntegerField(verbose_name='特攻')),
                ('special_defense', models.IntegerField(verbose_name='特防')),
                ('speed', models.IntegerField(verbose_name='素早さ')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=5, verbose_name='タイプ')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pokemon')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PokemonType')),
            ],
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='pokemons',
            field=models.ManyToManyField(related_name='pokemons', through='blog.PokemonTypeRelation', to='blog.Pokemon'),
        ),
    ]
