# Generated by Django 3.0 on 2022-05-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220429_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonPredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(blank=True, max_length=12, null=True, verbose_name='名前')),
                ('proba', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.PokemonImage')),
            ],
        ),
    ]
